[tool.poetry]
name = "aiofutures"
version = "0.1.0"
description = "Smoothly migrate your synchronous codebase to an asynchronous style."
authors = ["Denis Kazakov <denis@kazakov.ru.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
